# -*- coding: utf-8 -*-
"""Projeto_CineSentimento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Iu7sjSnLl079MONI8NLLJGNM3kEjhYA

### Guia de Estudo sobre analise de sentimentos

1.**Ana Isabel Silva Rodrigues <br>
2.**Simão Costa e Sá<br>
3.**Joel Valentim Pereira da Cunha<br>
4.**César Filipe Silva Ribeiro<br>
5.**Sandro Ribeiro dos Santos Junior<br>
"""

import pandas as pd

data = {
    "critica": [
        "Um filme absolutamente deslumbrante, adorei cada segundo.",
        "A atuação foi fraca e o enredo não fazia sentido nenhum.",
        "Tecnicamente brilhante, mas a história podia ser mais cativante.",
        "Que deceção! Dinheiro e tempo desperdiçados."
    ],
    "Sentimento": [
        "Positivo",
        "Negativo",
        "Positivo",
        "Negativo"
    ]
}

df = pd.DataFrame(data)
contagem_sentimentos = df["Sentimento"].value_counts()

print(df.head(2))

print(contagem_sentimentos)